// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SampleFeature.Infrastructure.Persistence;

#nullable disable

namespace SampleFeature.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SampleFeaturePersistenceDbContext))]
    [Migration("20260412105642_InitialSampleFeature")]
    partial class InitialSampleFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sample_feature")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SampleFeature.Infrastructure.Persistence.SampleAnnouncementRecord", b =>
                {
                    b.Property<Guid>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("announcement_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("PublishedByActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("published_by_actor_id");

                    b.Property<DateTimeOffset>("PublishedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("AnnouncementId");

                    b.ToTable("announcements", "sample_feature");
                });

            modelBuilder.Entity("SampleFeature.Infrastructure.Persistence.ScheduledSampleAnnouncementRecord", b =>
                {
                    b.Property<Guid>("ScheduledAnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("scheduled_announcement_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<DateTimeOffset?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until_utc");

                    b.Property<string>("LocalTimeResolution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("local_time_resolution");

                    b.Property<Guid?>("PublishedAnnouncementId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_announcement_id");

                    b.Property<DateTimeOffset?>("PublishedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_utc");

                    b.Property<string>("ScheduledByActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scheduled_by_actor_id");

                    b.Property<DateTimeOffset>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for_utc");

                    b.Property<DateOnly>("ScheduledLocalDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_local_date");

                    b.Property<TimeOnly>("ScheduledLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_local_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("ScheduledAnnouncementId");

                    b.HasIndex("ScheduledByActorId", "ScheduledForUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sample_feature_scheduled_announcements_actor");

                    b.HasIndex("Status", "ScheduledForUtc")
                        .HasDatabaseName("ix_sample_feature_scheduled_announcements_due");

                    b.ToTable("scheduled_announcements", "sample_feature");
                });
#pragma warning restore 612, 618
        }
    }
}
