<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\KnowledgeBase.Application\KnowledgeBase.Application.csproj" />
    <ProjectReference Include="..\KnowledgeBase.Infrastructure\KnowledgeBase.Infrastructure.csproj" />
    <ProjectReference Include="..\KnowledgeBase.PublicContracts\KnowledgeBase.PublicContracts.csproj" />
  </ItemGroup>
</Project>
