<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\Domain\BuildingBlocks.Domain.csproj" />
  </ItemGroup>
</Project>