// <auto-generated />
using System;
using Blog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BlogPersistenceDbContext))]
    [Migration("20260410220323_AddBlogModuleSettings")]
    partial class AddBlogModuleSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("blog")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blog.Infrastructure.Persistence.BlogCategoryRecord", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("UpdatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by_actor_id");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Slug");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_blog_categories_name");

                    b.ToTable("blog_categories", "blog");
                });

            modelBuilder.Entity("Blog.Infrastructure.Persistence.BlogPostRecord", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("CategorySlug")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category_slug");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean")
                        .HasColumnName("featured");

                    b.Property<string>("PublishedByActorId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("published_by_actor_id");

                    b.Property<DateTimeOffset?>("PublishedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_utc");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoKeywords")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("seo_keywords");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("seo_title");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by_actor_id");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.HasKey("PostId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_blog_posts_slug");

                    b.HasIndex("Status", "PublishedUtc")
                        .HasDatabaseName("ix_blog_posts_status_published_utc");

                    b.ToTable("blog_posts", "blog");
                });

            modelBuilder.Entity("Blog.Infrastructure.Persistence.BlogPostRevisionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("CategorySlug")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category_slug");

                    b.Property<string>("CreatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_actor_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean")
                        .HasColumnName("featured");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<int>("PostVersion")
                        .HasColumnType("integer")
                        .HasColumnName("post_version");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoKeywords")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("seo_keywords");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("seo_title");

                    b.Property<string>("ShareTargetsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("share_targets_json");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("summary");

                    b.Property<string>("TagNamesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag_names_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_blog_post_revisions_post_id_revision_number");

                    b.ToTable("blog_post_revisions", "blog");
                });

            modelBuilder.Entity("Blog.Infrastructure.Persistence.BlogPostScheduleRecord", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("ScheduledPublishByActorId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("scheduled_publish_by_actor_id");

                    b.Property<DateTimeOffset?>("ScheduledPublishForUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_publish_for_utc");

                    b.Property<DateOnly?>("ScheduledPublishLocalDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_publish_local_date");

                    b.Property<TimeOnly?>("ScheduledPublishLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_publish_local_time");

                    b.Property<string>("ScheduledPublishLocalTimeResolution")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scheduled_publish_local_time_resolution");

                    b.Property<string>("ScheduledPublishTimeZoneId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("scheduled_publish_time_zone_id");

                    b.Property<string>("ScheduledUnpublishByActorId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("scheduled_unpublish_by_actor_id");

                    b.Property<DateTimeOffset?>("ScheduledUnpublishForUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_unpublish_for_utc");

                    b.Property<DateOnly?>("ScheduledUnpublishLocalDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_unpublish_local_date");

                    b.Property<TimeOnly?>("ScheduledUnpublishLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_unpublish_local_time");

                    b.Property<string>("ScheduledUnpublishLocalTimeResolution")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scheduled_unpublish_local_time_resolution");

                    b.Property<string>("ScheduledUnpublishTimeZoneId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("scheduled_unpublish_time_zone_id");

                    b.Property<string>("UpdatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by_actor_id");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("PostId");

                    b.HasIndex("ScheduledPublishForUtc")
                        .HasDatabaseName("ix_blog_post_publication_schedules_publish_utc");

                    b.HasIndex("ScheduledUnpublishForUtc")
                        .HasDatabaseName("ix_blog_post_publication_schedules_unpublish_utc");

                    b.ToTable("blog_post_publication_schedules", "blog");
                });

            modelBuilder.Entity("Blog.Infrastructure.Persistence.BlogPostShareTargetRecord", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("Target")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target");

                    b.HasKey("PostId", "Target");

                    b.ToTable("blog_post_share_targets", "blog");
                });

            modelBuilder.Entity("Blog.Infrastructure.Persistence.BlogPostTagRecord", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("TagSlug")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tag_slug");

                    b.HasKey("PostId", "TagSlug");

                    b.HasIndex("TagSlug")
                        .HasDatabaseName("ix_blog_post_tags_tag_slug");

                    b.ToTable("blog_post_tags", "blog");
                });

            modelBuilder.Entity("Blog.Infrastructure.Persistence.BlogSettingsRecord", b =>
                {
                    b.Property<string>("SettingsKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("settings_key");

                    b.Property<string>("OperatorSummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("operator_summary");

                    b.Property<int>("PreviewLimit")
                        .HasColumnType("integer")
                        .HasColumnName("preview_limit");

                    b.Property<string>("UpdatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by_actor_id");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("SettingsKey");

                    b.ToTable("blog_module_settings", "blog");
                });

            modelBuilder.Entity("Blog.Infrastructure.Persistence.BlogTagRecord", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("UpdatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by_actor_id");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Slug");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_blog_tags_display_name");

                    b.ToTable("blog_tags", "blog");
                });

            modelBuilder.Entity("Blog.Infrastructure.Persistence.BlogPostRevisionRecord", b =>
                {
                    b.HasOne("Blog.Infrastructure.Persistence.BlogPostRecord", "Post")
                        .WithMany("Revisions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Blog.Infrastructure.Persistence.BlogPostScheduleRecord", b =>
                {
                    b.HasOne("Blog.Infrastructure.Persistence.BlogPostRecord", "Post")
                        .WithOne("PublicationSchedule")
                        .HasForeignKey("Blog.Infrastructure.Persistence.BlogPostScheduleRecord", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Blog.Infrastructure.Persistence.BlogPostShareTargetRecord", b =>
                {
                    b.HasOne("Blog.Infrastructure.Persistence.BlogPostRecord", "Post")
                        .WithMany("ShareTargets")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Blog.Infrastructure.Persistence.BlogPostTagRecord", b =>
                {
                    b.HasOne("Blog.Infrastructure.Persistence.BlogPostRecord", "Post")
                        .WithMany("Tags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Blog.Infrastructure.Persistence.BlogPostRecord", b =>
                {
                    b.Navigation("PublicationSchedule");

                    b.Navigation("Revisions");

                    b.Navigation("ShareTargets");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
