<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\Blog.Application\Blog.Application.csproj" />
    <ProjectReference Include="..\Blog.Infrastructure\Blog.Infrastructure.csproj" />
    <ProjectReference Include="..\Blog.PublicContracts\Blog.PublicContracts.csproj" />
  </ItemGroup>
</Project>
