<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Infrastructure\BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\Blog.Application\Blog.Application.csproj" />
    <ProjectReference Include="..\Blog.Domain\Blog.Domain.csproj" />
    <ProjectReference Include="..\Blog.PublicContracts\Blog.PublicContracts.csproj" />
  </ItemGroup>
</Project>
